Module 5
pcoulso1/DevOps-Course-Starter pull request #6
Opened 2020-09-13 09:03 UTC by pcoulso1

Pull request for adding a Dockerfile to the project

2020-09-17 18:40 UTC, hugh-emerson requested changes
Generally looks good, you're almost there. There's just one small requirement mentioned in the brief which you haven't done: it asks you to run the app with gunicorn in the production image.

I've also left some other suggestions.

2020-09-17 18:40 UTC, hugh-emerson commented on Dockerfile
> +CMD [ "flask", "run", "--no-reload", "--host=0.0.0.0"]
The exercise brief says:
> Make sure your app is running with gunicorn, rather than using flask run. Flask's development server is not suitable for production use.

2020-09-17 18:40 UTC, hugh-emerson commented on README.md
> +docker build --target development --tag pcoulso1/devops-course-starter:dev-v0.1 .
No need to tell everyone to include pcoulso1 in their tags.

2020-09-17 18:40 UTC, hugh-emerson commented on Dockerfile
> +COPY *.py ./
Your development image should be run with a mounted volume **instead of** copying files into the image.

i.e. this should just be in the production section.

2020-09-17 18:40 UTC, hugh-emerson commented on Dockerfile
> +COPY .env.template .env
Now that you're using --env-file in the docker run command, you can delete this line and `!.env.template` in the dockerignore file.

And since the .env files are ignored, can you COPY everything in one command instead of .py and templates separately?

2020-09-17 18:40 UTC, hugh-emerson commented on README.md
> +docker run -p 80:5000 --env-file .env --mount type=bind,source=<pwd>,target=/usr/src/app -d pcoulso1/devops-course-starter:prod-v0.1
You mean `dev` in the tag rather than `prod`

You can write "$(pwd)" instead of <pwd> so the reader doesn't need to customise the command.

Same for the below docker run command.

2020-09-17 18:40 UTC, hugh-emerson commented on Dockerfile
> +RUN pip install --no-cache-dir -r requirements.txt
Your app has both poetry and pip files, it would be nice to use just one.
Poetry is preferred, as it is nicer to work with than pip and it also handles venv.

2020-09-21 08:30 UTC, pcoulso1 commented on Dockerfile
> +CMD [ "flask", "run", "--no-reload", "--host=0.0.0.0"]
done

2020-09-21 08:31 UTC, pcoulso1 commented on README.md
> +docker build --target development --tag pcoulso1/devops-course-starter:dev-v0.1 .
removed pcoulso1

2020-09-21 08:31 UTC, pcoulso1 commented on Dockerfile
> +COPY *.py ./
Done

2020-09-21 08:31 UTC, pcoulso1 commented on Dockerfile
> +COPY .env.template .env
Done

2020-09-21 08:31 UTC, pcoulso1 commented on README.md
> +docker run -p 80:5000 --env-file .env --mount type=bind,source=<pwd>,target=/usr/src/app -d pcoulso1/devops-course-starter:prod-v0.1
Done

2020-09-25 15:58 UTC, hugh-emerson approved these changes
Looks good. I think it's worth deleting the obsolete files like requirements.txt and setup.sh (if you update the README to reference poetry instead) but merge when you're ready.

2020-10-16 14:21 UTC, merged